name: viz-agent
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # core scientific
  - numpy
  - scipy
  - pandas
  # - vmd-python  # Replaced with mdanalysis + nglview due to VTK conflicts with topologytoolkit
  - mdanalysis
  - nglview
  # - scikit-image
  # - scikit-learn
  # plotting
  - matplotlib
  - paraview
  # - seaborn
  # - plotly
  # - bokeh
  # - holoviews
  # - hvplot
  # - panel
  # 3D / volume / mesh visualization
  # - vtk
  # - pyvista
  # - mayavi
  - topologytoolkit
  # - imageio
  # - imageio-ffmpeg
  # napari ecosystem
  - napari
  # - magicgui
  # - napari-plugin-engine
  # notebooks
  # - jupyterlab
  # - ipykernel
  # - ipywidgets
  # helper tools
  - click
  - rich
